apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stressed-pod.fullname" . }}
  labels:
    {{- include "stressed-pod.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "stressed-pod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stressed-pod.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.name | default "squent/stressed-pod" }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: {{ include "stressed-pod.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: /probes/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /probes/readiness
              port: http 