{{- if or .Values.kumaIngressWatcher.ingress.enabled .Values.kumaIngressWatcher.ingressRoute.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
rules:
  {{- if .Values.kumaIngressWatcher.ingress.enabled }}
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  {{- end }}
  {{- if .Values.kumaIngressWatcher.ingressRoute.enabled }}
  - apiGroups: ["traefik.containo.us", "traefik.io"]
    resources: ["ingressroutes"]
    verbs: ["get", "list", "watch"]
  {{- end }}
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
{{- end }}