{{- if or .Values.kumaIngressWatcher.ingress.enabled .Values.kumaIngressWatcher.ingressRoute.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name | default "kuma-ingress-watcher" }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ "kuma-ingress-watcher" }}
  template:
    metadata:
      labels:
        app: {{ "kuma-ingress-watcher" }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: controller
        ports:
        - containerPort: 4025
          protocol: TCP
        image: "{{ .Values.deployment.image.name | default "squent/kuma-ingress-watcher" }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        stdin: true
        env:
        - name: LOG_LEVEL
          value: "{{ .Values.deployment.logLevel }}"
        - name: UPTIME_KUMA_URL
          value: "{{ .Values.uptimeKuma.url }}"
        - name: WATCH_INTERVAL
          value: "{{ .Values.kumaIngressWatcher.watchInterval | default `10` }}"
        - name: WATCH_INGRESSROUTES
          value: "{{ .Values.kumaIngressWatcher.ingressRoute.enabled }}"
        - name: USE_TRAEFIK_V3_CRD_GROUP
          value: "{{ .Values.kumaIngressWatcher.ingressRoute.traefikv3 }}"
        - name: WATCH_INGRESS
          value: "{{ .Values.kumaIngressWatcher.ingress.enabled }}"
        - name: UPTIME_KUMA_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.uptimeKuma.credentialsSecret }}
              key: user
        - name: UPTIME_KUMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.uptimeKuma.credentialsSecret }}
              key: password
        - name: ENABLE_FILE_MONITOR
          value: "{{ .Values.kumaIngressWatcher.fileBasedMonitors.enabled | default `false` }}"
        - name: MONITORS_FILE_PATH
          value: "{{ .Values.kumaIngressWatcher.fileBasedMonitors.monitorsFilePath | default `/etc/kuma/monitors.yaml` }}"
        - name: DEFAULT_PARENT
          value: "{{ .Values.uptimeKuma.defaultParent }}"
        {{- if .Values.kumaIngressWatcher.fileBasedMonitors.enabled }}
        volumeMounts:
        - name: monitors-file
          mountPath: "{{ .Values.kumaIngressWatcher.fileBasedMonitors.monitorsFilePath | default `/etc/kuma/monitors.yaml` }}"
          subPath: monitors.yaml
        {{- end }}
      {{- if .Values.kumaIngressWatcher.fileBasedMonitors.enabled }}
      volumes:
      - name: monitors-file
        configMap:
          name: {{ .Release.Name }}-monitors
      {{- end }}
{{- end }}