{{- if and .Values.kumaIngressWatcher.fileBasedMonitors.enabled (not .Values.kumaIngressWatcher.ingress.enabled) (not .Values.kumaIngressWatcher.ingressRoute.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.deployment.name | default "kuma-ingress-watcher-job" }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ "kuma-ingress-watcher" }}
    spec:
      restartPolicy: Never
      containers:
      - name: controller
        ports:
        - containerPort: 4025
          protocol: TCP
        image: "{{ .Values.deployment.image.name | default "squent/kuma-ingress-watcher" }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        stdin: true
        env:
        - name: LOG_LEVEL
          value: "{{ .Values.deployment.logLevel }}"
        - name: UPTIME_KUMA_URL
          value: "{{ .Values.uptimeKuma.url }}"
        - name: WATCH_INGRESSROUTES
          value: "{{ .Values.kumaIngressWatcher.ingressRoute.enabled }}"
        - name: WATCH_INGRESS
          value: "{{ .Values.kumaIngressWatcher.ingress.enabled }}"
        - name: WATCH_INTERVAL
          value: "{{ .Values.kumaIngressWatcher.watchInterval | default `10` }}"
        - name: ENABLE_FILE_MONITOR
          value: "{{ .Values.kumaIngressWatcher.fileBasedMonitors.enabled | default `false` }}"
        - name: MONITORS_FILE_PATH
          value: "{{ .Values.kumaIngressWatcher.fileBasedMonitors.monitorsFilePath | default `/etc/kuma-controller/monitors.yaml` }}"
        - name: UPTIME_KUMA_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.uptimeKuma.credentialsSecret }}
              key: user
        - name: UPTIME_KUMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.uptimeKuma.credentialsSecret }}
              key: password
        volumeMounts:
        - name: monitors-file
          mountPath: "{{ .Values.kumaIngressWatcher.fileBasedMonitors.monitorsFilePath | default `/etc/kuma-controller/monitors.yaml` }}"
          subPath: monitors.yaml
      volumes:
      - name: monitors-file
        configMap:
          name: {{ .Release.Name }}-monitors
{{- end }}
