{{- if or .Values.kumaIngressWatcher.ingress.enabled .Values.kumaIngressWatcher.ingressRoute.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
{{- end }}